/* dropping tables */

DROP TABLE PHONE;

DROP TABLE EMPLOYEE;

DROP TABLE DEPARTMENT;


/* create tables and their constraints */

CREATE TABLE DEPARTMENT
( 
 DEPARTMENT_ID NUMBER(5),
 DEPARTMENT_NAME VARCHAR2(30)
);

ALTER TABLE DEPARTMENT ADD
(
 CONSTRAINT PK_DEPARTMENT_ID
 PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE EMPLOYEE
( 
 EMPLOYEE_ID NUMBER(5),
 FIRSTNAME VARCHAR2(30),
 LASTNAME VARCHAR2(30),
 DEPARTMENT_ID NUMBER(5)
);

ALTER TABLE EMPLOYEE ADD
(
 CONSTRAINT PK_EMPLOYEE_ID
 PRIMARY KEY (EMPLOYEE_ID)
);

ALTER TABLE EMPLOYEE ADD
(
 CONSTRAINT FK_DEPARTMENT_ID
 FOREIGN KEY (DEPARTMENT_ID)
 REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE PHONE 
(
 PHONE_ID NUMBER(5),
 PHONE_NUMBER VARCHAR2(15),
 EMPLOYEE_ID NUMBER(5)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT PK_PHONE_ID
 PRIMARY KEY(PHONE_ID)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT FK_EMPLOYEE_ID
 FOREIGN KEY(EMPLOYEE_ID)
 REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


/* drop sequences */

DROP SEQUENCE DEPT_SEQ;

DROP SEQUENCE EMP_SEQ;

DROP SEQUENCE PHONE_SEQ;

/*  create sequences */

CREATE SEQUENCE DEPT_SEQ
 START WITH 10
 INCREMENT BY 10;

CREATE SEQUENCE EMP_SEQ
 START WITH 101
 INCREMENT BY 1;

CREATE SEQUENCE PHONE_SEQ
 START WITH 1
 INCREMENT BY 1;

/* inserting data into static tables */

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'TRANSPORT');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'MARKETING');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'DEVELOPMENT');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'HR DEPT');


COMMIT;



