/* dropping tables */

DROP TABLE PHONE;

DROP TABLE PHONE_TYPE;

DROP TABLE EMAIL;

DROP TABLE EMAIL_TYPE;

DROP TABLE EMPLOYEE;

DROP TABLE DEPARTMENT;


/* creating tables and their constraints */

/* creating department table & its constraints */

CREATE TABLE DEPARTMENT
( 
 DEPARTMENT_ID NUMBER(5),
 DEPARTMENT_NAME VARCHAR2(30)
);

ALTER TABLE DEPARTMENT ADD
(
 CONSTRAINT PK_DEPARTMENT_ID
 PRIMARY KEY (DEPARTMENT_ID)
);


/* creating employee table & its constraints */

CREATE TABLE EMPLOYEE
( 
 EMPLOYEE_ID NUMBER(5),
 FIRSTNAME VARCHAR2(30),
 LASTNAME VARCHAR2(30),
 DOB DATE,
 DEPARTMENT_ID NUMBER(5)
);

ALTER TABLE EMPLOYEE ADD
(
 CONSTRAINT PK_EMPLOYEE_ID
 PRIMARY KEY (EMPLOYEE_ID)
);

ALTER TABLE EMPLOYEE ADD
(
 CONSTRAINT FK_DEPARTMENT_ID
 FOREIGN KEY (DEPARTMENT_ID)
 REFERENCES DEPARTMENT(DEPARTMENT_ID)
);


/* creating phone_type table & its constraints */

CREATE TABLE PHONE_TYPE
(
 PHONE_TYPE_ID NUMBER(5),
 PHONE_TYPE VARCHAR2(30)
);

ALTER TABLE PHONE_TYPE ADD
(
 CONSTRAINT PK_PHONE_TYPE_ID
 PRIMARY KEY(PHONE_TYPE_ID)
);


/* creating phone table & its constraints */

CREATE TABLE PHONE 
(
 PHONE_ID NUMBER(5),
 EMPLOYEE_ID NUMBER(5),
 PHONE_TYPE_ID NUMBER(5),
 PHONE_NUMBER VARCHAR2(15)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT PK_PHONE_ID
 PRIMARY KEY(PHONE_ID)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT FK_PHONE_EMPLOYEE_ID
 FOREIGN KEY(EMPLOYEE_ID)
 REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT FK_PHONE_TYPE_ID
 FOREIGN KEY(PHONE_TYPE_ID)
 REFERENCES PHONE_TYPE(PHONE_TYPE_ID)
);



/* creating email_type table & its constraints */


CREATE TABLE EMAIL_TYPE
(
 EMAIL_TYPE_ID NUMBER(5),
 EMAIL_TYPE VARCHAR2(30)
);

ALTER TABLE EMAIL_TYPE ADD
(
 CONSTRAINT PK_EMAIL_TYPE_ID
 PRIMARY KEY(EMAIL_TYPE_ID)
);


/* creating email table & its constraints */

CREATE TABLE EMAIL 
(
 EMAIL_ID NUMBER(5),
 EMPLOYEE_ID NUMBER(5),
 EMAIL_TYPE_ID NUMBER(5),
 EMAIL VARCHAR2(30)
);

ALTER TABLE EMAIL ADD
(
 CONSTRAINT PK_EMAIL_ID
 PRIMARY KEY(EMAIL_ID)
);

ALTER TABLE EMAIL ADD
(
 CONSTRAINT FK_EMAIL_EMPLOYEE_ID
 FOREIGN KEY(EMPLOYEE_ID)
 REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

ALTER TABLE EMAIL ADD
(
 CONSTRAINT FK_EMAIL_TYPE_ID
 FOREIGN KEY(EMAIL_TYPE_ID)
 REFERENCES EMAIL_TYPE(EMAIL_TYPE_ID)
);


/* drop sequences */

DROP SEQUENCE DEPT_SEQ;

DROP SEQUENCE EMP_SEQ;

DROP SEQUENCE PHONE_SEQ;

DROP SEQUENCE PHONE_TYPE_SEQ;

DROP SEQUENCE EMAIL_SEQ;

DROP SEQUENCE EMAIL_TYPE_SEQ;


/*  create sequences */

CREATE SEQUENCE DEPT_SEQ
 START WITH 10
 INCREMENT BY 10;

CREATE SEQUENCE EMP_SEQ
 START WITH 101
 INCREMENT BY 1;

CREATE SEQUENCE PHONE_TYPE_SEQ
 START WITH 10
 INCREMENT BY 10;

CREATE SEQUENCE PHONE_SEQ
 START WITH 1
 INCREMENT BY 1;

CREATE SEQUENCE EMAIL_TYPE_SEQ
 START WITH 10
 INCREMENT BY 10;

CREATE SEQUENCE EMAIL_SEQ
 START WITH 1
 INCREMENT BY 1;




/* inserting data into static tables */

/* inserting data into department table*/

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'TRANSPORT');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'MARKETING');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'DEVELOPMENT');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'HR DEPT');


/* inserting data into phone_type table*/

INSERT INTO PHONE_TYPE(PHONE_TYPE_ID, PHONE_TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL,'MOBILE');

INSERT INTO PHONE_TYPE(PHONE_TYPE_ID, PHONE_TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL,'HOME');

INSERT INTO PHONE_TYPE(PHONE_TYPE_ID, PHONE_TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL,'OFFICE');


/* inserting data into email_type table*/

INSERT INTO EMAIL_TYPE(EMAIL_TYPE_ID, EMAIL_TYPE) VALUES (EMAIL_TYPE_SEQ.NEXTVAL,'PERSONAL');

INSERT INTO EMAIL_TYPE(EMAIL_TYPE_ID, EMAIL_TYPE) VALUES (EMAIL_TYPE_SEQ.NEXTVAL,'OFFICIAL');




COMMIT;



