/* dropping tables */

DROP TABLE PHONE;

DROP TABLE PHONE_TYPE;

DROP TABLE EMAIL;

DROP TABLE EMAIL_TYPE;

DROP TABLE EMPLOYEE;

DROP TABLE DEPARTMENT;


/* creating tables and their constraints */

/* creating department table & its constraints */

CREATE TABLE DEPARTMENT
( 
 DEPARTMENT_ID NUMBER(5),
 DEPARTMENT_NAME VARCHAR2(30)
);

ALTER TABLE DEPARTMENT ADD
(
 CONSTRAINT PK_DEPARTMENT_ID
 PRIMARY KEY (DEPARTMENT_ID)
);


/* creating employee table & its constraints */

CREATE TABLE EMPLOYEE
( 
 EMPLOYEE_ID NUMBER(5),
 FIRSTNAME VARCHAR2(30),
 LASTNAME VARCHAR2(30),
 DOB DATE,
 DEPARTMENT_ID NUMBER(5)
);

ALTER TABLE EMPLOYEE ADD
(
 CONSTRAINT PK_EMPLOYEE_ID
 PRIMARY KEY (EMPLOYEE_ID)
);

ALTER TABLE EMPLOYEE ADD
(
 CONSTRAINT FK_DEPARTMENT_ID
 FOREIGN KEY (DEPARTMENT_ID)
 REFERENCES DEPARTMENT(DEPARTMENT_ID)
);


/* creating phone_type table & its constraints */

CREATE TABLE PHONE_TYPE
(
 PHONE_TYPE_ID NUMBER(5),
 PHONE_TYPE VARCHAR2(30)
);

ALTER TABLE PHONE_TYPE ADD
(
 CONSTRAINT PK_PHONE_TYPE_ID
 PRIMARY KEY(PHONE_TYPE_ID)
);


/* creating phone table & its constraints */

CREATE TABLE PHONE 
(
 PHONE_ID NUMBER(5),
 EMPLOYEE_ID NUMBER(5),
 PHONE_TYPE_ID NUMBER(5),
 PHONE_NUMBER VARCHAR2(15)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT PK_PHONE_ID
 PRIMARY KEY(PHONE_ID)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT FK_PHONE_EMPLOYEE_ID
 FOREIGN KEY(EMPLOYEE_ID)
 REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

ALTER TABLE PHONE ADD
(
 CONSTRAINT FK_PHONE_TYPE_ID
 FOREIGN KEY(PHONE_TYPE_ID)
 REFERENCES PHONE_TYPE(PHONE_TYPE_ID)
);



/* creating email_type table & its constraints */


CREATE TABLE EMAIL_TYPE
(
 EMAIL_TYPE_ID NUMBER(5),
 EMAIL_TYPE VARCHAR2(30)
);

ALTER TABLE EMAIL_TYPE ADD
(
 CONSTRAINT PK_EMAIL_TYPE_ID
 PRIMARY KEY(EMAIL_TYPE_ID)
);


/* creating email table & its constraints */

CREATE TABLE EMAIL 
(
 EMAIL_ID NUMBER(5),
 EMPLOYEE_ID NUMBER(5),
 EMAIL_TYPE_ID NUMBER(5),
 EMAIL VARCHAR2(30)
);

ALTER TABLE EMAIL ADD
(
 CONSTRAINT PK_EMAIL_ID
 PRIMARY KEY(EMAIL_ID)
);

ALTER TABLE EMAIL ADD
(
 CONSTRAINT FK_EMAIL_EMPLOYEE_ID
 FOREIGN KEY(EMPLOYEE_ID)
 REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

ALTER TABLE EMAIL ADD
(
 CONSTRAINT FK_EMAIL_TYPE_ID
 FOREIGN KEY(EMAIL_TYPE_ID)
 REFERENCES EMAIL_TYPE(EMAIL_TYPE_ID)
);


/* drop sequences */

DROP SEQUENCE DEPT_SEQ;

DROP SEQUENCE EMP_SEQ;

DROP SEQUENCE PHONE_SEQ;

DROP SEQUENCE PHONE_TYPE_SEQ;

DROP SEQUENCE EMAIL_SEQ;

DROP SEQUENCE EMAIL_TYPE_SEQ;


/*  create sequences */

CREATE SEQUENCE DEPT_SEQ
 START WITH 10
 INCREMENT BY 10;

CREATE SEQUENCE EMP_SEQ
 START WITH 101
 INCREMENT BY 1;

CREATE SEQUENCE PHONE_TYPE_SEQ
 START WITH 10
 INCREMENT BY 10;

CREATE SEQUENCE PHONE_SEQ
 START WITH 1
 INCREMENT BY 1;

CREATE SEQUENCE EMAIL_TYPE_SEQ
 START WITH 10
 INCREMENT BY 10;

CREATE SEQUENCE EMAIL_SEQ
 START WITH 1
 INCREMENT BY 1;




/* inserting data into static tables */

/* inserting data into department table*/

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'TRANSPORT');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'MARKETING');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'DEVELOPMENT');

INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (DEPT_SEQ.NEXTVAL,'HR DEPT');


/* inserting data into phone_type table*/

INSERT INTO PHONE_TYPE(PHONE_TYPE_ID, PHONE_TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL,'MOBILE');

INSERT INTO PHONE_TYPE(PHONE_TYPE_ID, PHONE_TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL,'HOME');

INSERT INTO PHONE_TYPE(PHONE_TYPE_ID, PHONE_TYPE) VALUES (PHONE_TYPE_SEQ.NEXTVAL,'OFFICE');


/* inserting data into email_type table*/

INSERT INTO EMAIL_TYPE(EMAIL_TYPE_ID, EMAIL_TYPE) VALUES (EMAIL_TYPE_SEQ.NEXTVAL,'PERSONAL');

INSERT INTO EMAIL_TYPE(EMAIL_TYPE_ID, EMAIL_TYPE) VALUES (EMAIL_TYPE_SEQ.NEXTVAL,'OFFICIAL');


/* inserting data into dynamic tables */

/* inserting  AAA employee details*/


INSERT INTO EMPLOYEE(EMPLOYEE_ID,FIRSTNAME,LASTNAME,DOB,DEPARTMENT_ID) VALUES (EMP_SEQ.NEXTVAL,'AAA','A',TO_DATE('26/12/1998','DD/MM/YYYY'),(SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE DEPARTMENT_NAME='TRANSPORT'));


INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='MOBILE'),111);

INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='HOME'),1111);

INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='OFFICE'),11111);


INSERT INTO EMAIL(EMAIL_ID,EMPLOYEE_ID,EMAIL_TYPE_ID,EMAIL) VALUES(EMAIL_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT EMAIL_TYPE_ID FROM EMAIL_TYPE WHERE EMAIL_TYPE='PERSONAL'),'AA@GMAIL.COM');

INSERT INTO EMAIL(EMAIL_ID,EMPLOYEE_ID,EMAIL_TYPE_ID,EMAIL) VALUES(EMAIL_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT EMAIL_TYPE_ID FROM EMAIL_TYPE WHERE EMAIL_TYPE='OFFICIAL'),'AA@CLUSTER.COM');


/* inserting BBB employee details*/


INSERT INTO EMPLOYEE(EMPLOYEE_ID,FIRSTNAME,LASTNAME,DOB,DEPARTMENT_ID) VALUES (EMP_SEQ.NEXTVAL,'BBB','B',TO_DATE('06/10/1994','DD/MM/YYYY'),(SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE DEPARTMENT_NAME='MARKETING'));


INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='MOBILE'),222);

INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='HOME'),2222);

INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='OFFICE'),22222);


INSERT INTO EMAIL(EMAIL_ID,EMPLOYEE_ID,EMAIL_TYPE_ID,EMAIL) VALUES(EMAIL_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT EMAIL_TYPE_ID FROM EMAIL_TYPE WHERE EMAIL_TYPE='PERSONAL'),'BB@GMAIL.COM');

INSERT INTO EMAIL(EMAIL_ID,EMPLOYEE_ID,EMAIL_TYPE_ID,EMAIL) VALUES(EMAIL_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT EMAIL_TYPE_ID FROM EMAIL_TYPE WHERE EMAIL_TYPE='OFFICIAL'),'BB@CLUSTER.COM');




/* inserting CCC employee details*/


INSERT INTO EMPLOYEE(EMPLOYEE_ID,FIRSTNAME,LASTNAME,DOB,DEPARTMENT_ID) VALUES (EMP_SEQ.NEXTVAL,'CCC','C',TO_DATE('12/05/2004','DD/MM/YYYY'),(SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE DEPARTMENT_NAME='DEVELOPMENT'));


INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='MOBILE'),333);

INSERT INTO PHONE(PHONE_ID,EMPLOYEE_ID,PHONE_TYPE_ID,PHONE_NUMBER) VALUES(PHONE_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT PHONE_TYPE_ID FROM PHONE_TYPE WHERE PHONE_TYPE='HOME'),3333);


INSERT INTO EMAIL(EMAIL_ID,EMPLOYEE_ID,EMAIL_TYPE_ID,EMAIL) VALUES(EMAIL_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT EMAIL_TYPE_ID FROM EMAIL_TYPE WHERE EMAIL_TYPE='PERSONAL'),'CC@GMAIL.COM');

INSERT INTO EMAIL(EMAIL_ID,EMPLOYEE_ID,EMAIL_TYPE_ID,EMAIL) VALUES(EMAIL_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT EMAIL_TYPE_ID FROM EMAIL_TYPE WHERE EMAIL_TYPE='OFFICIAL'),'CC@CLUSTER.COM');




/* inserting DDD employee details*/


INSERT INTO EMPLOYEE(EMPLOYEE_ID,FIRSTNAME,LASTNAME,DOB,DEPARTMENT_ID) VALUES (EMP_SEQ.NEXTVAL,'DDD','D',TO_DATE('08/03/2001','DD/MM/YYYY'),(SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE DEPARTMENT_NAME='MARKETING'));


INSERT INTO EMAIL(EMAIL_ID,EMPLOYEE_ID,EMAIL_TYPE_ID,EMAIL) VALUES(EMAIL_SEQ.NEXTVAL,EMP_SEQ.CURRVAL,(SELECT EMAIL_TYPE_ID FROM EMAIL_TYPE WHERE EMAIL_TYPE='OFFICIAL'),'DD@CLUSTER.COM');


COMMIT;



